# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GGLIST\Job\Software\Study\Python\20220523\lineeditTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 171)
        self.lbl_textHere = QtWidgets.QLabel(Dialog)
        self.lbl_textHere.setGeometry(QtCore.QRect(30, 50, 351, 16))
        self.lbl_textHere.setObjectName("lbl_textHere")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 351, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineedit_Test = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineedit_Test.setObjectName("lineedit_Test")
        self.horizontalLayout.addWidget(self.lineedit_Test)
        self.btn_changeText = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_changeText.setObjectName("btn_changeText")
        self.horizontalLayout.addWidget(self.btn_changeText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_textHere.setText(_translate("Dialog", "Text Here"))
        self.btn_changeText.setText(_translate("Dialog", "Change Label Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
